POST http://localhost/products
Content-Type: application/json

{
    "name" : "Pizza",
    "value": 35.99
}

###
GET http://localhost/products

###
GET http://localhost/products/ee2287f4-d618-4a92-9046-a2e87b3cd595

###
PUT http://localhost/products/f59a4b90-e0e6-411e-a835-c3e1eb1408ea
Content-Type: application/json

{
    "name" : "Pastel",
    "value": 35.99
}